
CREATE DATABASE IF NOT EXISTS ADF_TRAINING_DB;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
  WITH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE;

  USE DATABASE ADF_TRAINING_DB;
USE SCHEMA RAW;
SHOW TABLES;

USE DATABASE ADF_TRAINING_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE PRODUTOS (
    id_produto INT,
    nome_produto VARCHAR(100),
    preco DECIMAL(10,2)
);

CREATE OR REPLACE TABLE CLIENTES (
    id_cliente INT,
    nome VARCHAR(100),
    cidade VARCHAR(50)

);

CREATE OR REPLACE TABLE VENDAS (
    id_venda INT,
    id_cliente INT,
    id_produto INT,
    quantidade INT,
    valor_total DECIMAL(10,2)

);
USE DATABASE ADF_TRAINING_DB;
USE SCHEMA RAW;
SHOW TABLES;

-- Contagem de linhas
SELECT COUNT(*) AS TOTAL_CLIENTES FROM CLIENTES;
SELECT COUNT(*) AS TOTAL_PRODUTOS FROM PRODUTOS;
SELECT COUNT(*) AS TOTAL_VENDAS FROM VENDAS;

-- Verificação da ingestão dos dados
SELECT *
FROM VENDAS;
